### ISSUE TITLE
Improper release v0.6.12

### ISSUE THREAD

**Issue by sushant-pradhan-tm** [gruntwork-io/kubergrunt#119]
The most recent release v0.6.12 is [missing](https://github.com/gruntwork-io/kubergrunt/releases/tag/v0.6.12) required assets. Eg. of a previous release: https://github.com/gruntwork-io/kubergrunt/releases/download/v0.6.11/kubergrunt_linux_amd64

**Comment by yorinasub17** [comment]
Thanks for the report. This should be resolved now!
