### ISSUE TITLE
Kugergrunt using the wrong version for EKS 1.18

### ISSUE THREAD

**Issue by jasonmcintosh** [gruntwork-io/kubergrunt#136]
[] INFO[2021-08-19T14:05:49-05:00] Successfully retrieved EKS cluster details    name=kubergrunt
[] INFO[2021-08-19T14:05:49-05:00] Syncing Kubernetes Applications to:           name=kubergrunt
[] INFO[2021-08-19T14:05:49-05:00] 	kube-proxy:	1.18.8-eksbuild.2                name=kubergrunt

Per:
https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html#kube-proxy-default-versions-table

The currently supported release for 1.18 EKS cluters is:

1.18.8-eksbuild.1

1.18.8-eksbuild.2 doesn't exist and throws:
Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.18.8-eksbuild.2": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.18.8-eksbuild.2 not found: manifest unknown: Requested image not found

**Comment by yorinasub17** [comment]
This should be fixed in https://github.com/gruntwork-io/kubergrunt/releases/tag/v0.7.7 (binaries should show up shortly)

**Comment by jasonmcintosh** [comment]
AWESOME :) I like that not only was the issue fixed, it was done in such a way that actually goes beyond "here's a fixed list on the docs" but actually queries ECR!  Great work! :)
