### ISSUE TITLE
No --version flag when building from source

### ISSUE THREAD

**Issue by sre-ops** [gruntwork-io/kubergrunt#138]
Hi All,

When following the directions to build from source, the resultant binary does not have the --version flag available.  This causes downstream problems when working with other gruntworks modules, as most modules check the version of kubergrunt before using.  I am compiling with:

go build -o bin/kubergrunt ./cmd

Is there another flag or build config that I should use to make sure the --version flag gets included in kubergrunt?

For reference, here is the error encountered with kubergrunt built from latest source:

```
$ /usr/bin/kubergrunt --version
Incorrect Usage. flag provided but not defined: -version
Usage: kubergrunt [--loglevel] [--help] command [options] [args]
A CLI tool to help setup and manage a Kubernetes cluster.
Commands:
   eks      Helper commands to configure EKS.
   k8s      Helper scripts for managing Kubernetes resources directly.
   tls      Helper commands to manage TLS certificate key pairs as Kubernetes Secrets.
   help, h  Shows a list of commands or help for one command
ERROR: flag provided but not defined: -version
```

**Comment by yorinasub17** [comment]
Ah you need to pass in the ldflags to set the version at build time. The following should work:

```
go build -o kubergrunt -ldflags "-X main.VERSION=v0.7.6 -extldflags '-static'" ./cmd
```

We need to update the docs to mention this.
