### ISSUE TITLE
New VPC CNI version is available 

### ISSUE THREAD

**Issue by kjowong** [gruntwork-io/kubergrunt#143]
Hi! It looks like the VPC CNI has version 1.9.0 available per the docs:

https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on

Any feedback on opening issues is welcomed as I've never opened one before 😅

**Comment by yorinasub17** [comment]
Thanks for the bug report! This is now released as https://github.com/gruntwork-io/kubergrunt/releases/tag/v0.7.9 (binaries should show up in 15-30 mins)
