### ISSUE TITLE
--delete-local-data is deprecated; we should switch to --delete-emptydir-data

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/kubergrunt#145]
[Slack thread for context](https://gruntwork-community.slack.com/archives/CHH9Y3Z62/p1630424117093800).

`kubergrunt eks deploy` supports a `--delete-local-data` flag, but it looks like that has been deprecated:

```
Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.
```

Looks like we need to switch to `--delete-emptydir-data`.

**Comment by yorinasub17** [comment]
cc @autero1
