### ISSUE TITLE
New recommended VPC CNI version

### ISSUE THREAD

**Issue by martinlindner** [gruntwork-io/kubergrunt#164]
**Describe the bug**
AWS bumped VPC CNI a while ago, so kubergrunt 0.9.0 doesn't update the VPC CNI pods to the latest recommended version (1.11.0) anymore.
https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html

**To Reproduce**
Run `kubergrunt eks sync-core-components ..` -> VPC CNI is updated to `v1.10.2`.

**Expected behavior**
VPC CNI is updated to `v1.11.0`.

Happy to create a quick PR for this.

**Comment by autero1** [comment]
Fixed in #174
