### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/kubergrunt#206]
👋 it looks like [0.12.0](https://github.com/gruntwork-io/kubergrunt/releases/tag/v0.12.0) did not complete successfully, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/136856

**Comment by pras111gw** [comment]
Thanks @chenrui333 . v0.12 is still a draft release. It should be GA in next couple days.

**Comment by pras111gw** [comment]
Hi @chenrui333 Kubergrunt v0.12.0 has released. Please let us know if you see any issues installing it. Thanks.
