### ISSUE TITLE
Kubergrunt eks sync-core-components Error-message. Code: TOO_MANY_EKS_BUILD_TAGS

### ISSUE THREAD

**Issue by islamselim83** [gruntwork-io/kubergrunt#214]
**Describe the bug**
when we apply the modules/eks-cluster-control-plane it shows that error.
 kubergrunt eks sync-core-components --eks-cluster-arn arn:aws:eks:eu-central-1:1234567:cluster/#cluster-name# --wait
[] INFO[2023-11-21T09:31:34+01:00] Looking up deployed Kubernetes version        name=kubergrunt
[] INFO[2023-11-21T09:31:34+01:00] Retrieving details for EKS cluster arn:aws:eks:eu-central-1:12344567:cluster/#clustername#  name=kubergrunt
[] INFO[2023-11-21T09:31:34+01:00] Detected cluster deployed in region eu-central-1  name=kubergrunt
[] INFO[2023-11-21T09:31:34+01:00] Successfully retrieved EKS cluster details    name=kubergrunt
ERROR: You reached a point in kubergrunt that should not happen and is almost certainly a bug. Please open a GitHub issue on https://github.com/gruntwork-io/kubergrunt/issues with the contents of this error message. Code: TOO_MANY_EKS_BUILD_TAGS

**To Reproduce**
Steps to reproduce the behavior including the relevant Terraform/Terragrunt/Packer version number and any code snippets and module inputs you used.

We are trying to perform an EKS upgrade from v1.25 to v1.26 by using the terraform-aws-eks/modules/eks-cluster-control-plane Gruntwork module and we got that error when creating the null_resource.sync_core_components[0]

- terraform version: 1.5.2
- terragrunt version: 0.48.1
- terraform-aws-eks/modules/eks-cluster-control-plane version: 0.64.4

```hcl
// paste code snippets here
```

**Expected behavior**
not having errors

**Nice to have**

**Additional context**

**Comment by ryehowell** [comment]
Hi @islamselim83, thank you for reporting this issue. We are working to get one of the PR's merged now to address this issue.

**Comment by ryehowell** [comment]
Hi @islamselim83, the latest [release](https://github.com/gruntwork-io/kubergrunt/releases/tag/v0.13.1) fixes this issue.
