### ISSUE TITLE
helm rotate command that rotates the certs

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/kubergrunt#53]
This command should:

- Generate a new CA
- Generate new server side certs and do an inplace update on the existing Secret for Tiller.
- Generate new client side certs for each client previously granted and do an inplace update on the existing Secret for Tiller.

**Comment by sayanchowdhury** [comment]
this looks like an interesting issue. I'll try to create a PR for this issue.

**Comment by yorinasub17** [comment]
Helm features are removed, so this is no longer relevant.
