### ISSUE TITLE
Add ability to use environment variables for kubectl config

### ISSUE THREAD

**Issue by KyleMartin901** [gruntwork-io/kubergrunt#58]
Hi,

Just making a feature request for kubergrunt to have the ability to read the [Kubectl config variable](https://github.com/gruntwork-io/kubergrunt/blob/master/cmd/common.go#L268) from environment variable `KUBECONFIG` as well as the cli flags. I couldn't find anything in past issues so I apologise if you have already addressed this.

I am using [KIND](https://kind.sigs.k8s.io) to build the Kubernetes clusters and then use [direnv](https://direnv.net) to load the environment variable `KUBECONFIG` based on my different testing environments.

```
export KUBECONFIG="$(kind get kubeconfig-path --name="infra")"
```

[Terraform](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L64) and Kubectl both read what config to use from this environment variable `KUBECONFIG` and it would be awesome if Kubergrunt also did, making it even easier to use within Terraform with local exec, I would think at least for me it would. 

Thanks
Kyle

**Comment by yorinasub17** [comment]
Good idea! It looks like this might be fairly straightforward to add, since `urfave/cli` (the underlying library we use to build the CLI) supports [sourcing values from environment variable](https://github.com/urfave/cli#values-from-the-environment). Would you be up for a PR to try it out?

**Comment by KyleMartin901** [comment]
Thanks @yorinasub17 for some reason I missed the fact you could add the environment variable easily with the package.

I added it and submitted a pull request for it.
