### ISSUE TITLE
Getting secret name tiller-client-certs

### ISSUE THREAD

**Issue by bhegazy** [gruntwork-io/kubergrunt#66]
Hi, 
Thanks for the awesome tool, I have started to use kubergrunt but I was wondering if there is away to get or change a custom name for the tiller-client-certs, currently when doing `kubergrant helm grant` it will create certs with name `tiller-client-<random-number>-certs`

My use case is to get the secret name and then use it with [fluxcd](https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L49) without having to get the secrets using terraform data then recreate the secret again using `kubernetes_secret` which of course will expose the secrets to statefile.

Thanks

**Comment by bhegazy** [comment]
I took a look at the code and figured it was md5 hashed number so I'm currently had success getting the name using the following

```
  flux_namespace_sa = "${var.tiller_namespace}.${local.flux_service_account}"
  tls_client_secret_name = "tiller-client-${md5(local.flux_namespace_sa)}-certs"
```

**Comment by yorinasub17** [comment]
This should be doable, as long as all three commands (`grant`, `configure`, `revoke`) are updated to support this semantic. Right now `configure` and `revoke` use that name in some capacity to uniquely identify that secret.

On another note, does flux support looking up the secret by labels? We attach the label `gruntwork.io/tiller-entity-id` and `gruntwork.io/tiller-namespace` that you can use to look up the Secrets using more friendly strings.

**Comment by bhegazy** [comment]
Hi @yorinasub17 sorry for not getting back earlier, currently flux helm chart only able to get it by secret name, but currently using the workaround works well for me

```
tls_client_secret_name = "tiller-client-${md5(local.flux_namespace_sa)}-certs"
``` 

if you prefer the issue to be closed that's fine by me.

Thanks for your help

**Comment by yorinasub17** [comment]
Let's keep this open since I think it is a valid enhancement to make. With that said, this whole functionality will be deprecated soon once helm 3 reaches GA :)

**Comment by yorinasub17** [comment]
Helm features are removed, so this is no longer relevant.
