### ISSUE TITLE
Tiller-less version

### ISSUE THREAD

**Issue by andrevtg** [gruntwork-io/kubergrunt#75]
Could we make tiller deprecated or at least optional?

No need for it on Helm 3.

**Comment by yorinasub17** [comment]
As far as I know, for helm 3, the whole feature set of `kubergrunt helm` is unnecessary and thus not needed.

Is there a specific command that you think is usable with `kubergrunt` and "helm 3" that needs updates?

**Comment by andrevtg** [comment]
No, sorry, I actually misunderstood kubergrunt purpose/behaviour. Silly me, kinda late in here.
